Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
  # If true, strings which span multiple lines using \ for continuation must
  # use the same type of quotes on each line.
  ConsistentQuotesInMultiline: false
  Exclude:
    - "test/rails_app/app/mailers/*"
    - "test/es_rails_app/app/mailers/*"

Layout/ParameterAlignment:
  # Alignment of parameters in multi-line method calls.
  #
  # The `with_first_parameter` style aligns the following lines along the same
  # column as the first parameter.
  #
  #     method_call(a,
  #                 b)
  #
  # The `with_fixed_indentation` style aligns the following lines with one
  # level of indentation relative to the start of the line with the method call.
  #
  #     method_call(a,
  #       b)
  EnforcedStyle: with_fixed_indentation
  SupportedStyles:
    - with_first_parameter
    - with_fixed_indentation
  # By default, the indentation width from Style/IndentationWidth is used
  # But it can be overridden by setting this parameter
  # IndentationWidth: ~

Layout/LineLength:
  Max: 132
  # To make it possible to copy or click on URIs in the code, we allow lines
  # containing a URI to be longer than Max.
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https
  # The IgnoreCopDirectives option causes the LineLength rule to ignore cop
  # directives like '# rubocop: enable ...' when calculating a line's length.
  IgnoreCopDirectives: true
  # The IgnoredPatterns option is a list of !ruby/regexp and/or string
  # elements. Strings will be converted to Regexp objects. A line that matches
  # any regular expression listed in this option will be ignored by LineLength.
  IgnoredPatterns: []

# Rails 5 only requires 2.2.2.
AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.2
  # TargetRubyVersion: <%= RUBY_VERSION[/\d+\.\d+/] %>
  Exclude:
    - Capfile
    - Gemfile
    - "test/rails_app/bin/**/*"
    - "test/rails_app/config/**/*"
    - test/rails_app/config.ru
    - "test/rails_app/db/**/*"
    - "test/rails_app/log/**/*"
    - "test/rails_app/tmp/**/*"
    - "test/rails_app/vendor/**/*"
    - "test/rails_app/node_modules/**/*"
    - "test/rails_app/bower_components/**/*"
    - test/rails_app/Gemfile
    - test/rails_app/Guardfile
    - test/rails_app/Rakefile
    - "test/es_rails_app/bin/**/*"
    - "test/es_rails_app/config/**/*"
    - test/es_rails_app/config.ru
    - "test/es_rails_app/db/**/*"
    - "test/es_rails_app/log/**/*"
    - "test/es_rails_app/tmp/**/*"
    - "test/es_rails_app/vendor/**/*"
    - "test/es_rails_app/node_modules/**/*"
    - "test/es_rails_app/bower_components/**/*"
    - test/es_rails_app/Gemfile
    - test/es_rails_app/Guardfile
    - test/es_rails_app/Rakefile

Metrics/BlockLength:
  Exclude:
    - devise-bootstrap-form.gemspec

Metrics/AbcSize:
  Exclude:
    - test/**/*.rb

Metrics/ClassLength:
  Exclude:
    - test/**/*.rb

Metrics/MethodLength:
  Exclude:
    - test/**/*.rb

# TODO: Remove this when minimum Ruby is 2.3.
Layout/HeredocIndentation:
  Exclude:
    - Dangerfile
    - devise-bootstrap-form.gemspec
