language: ruby
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
before_install:
  - gem i rubygems-update -v '<3'
  - gem install bundler -v 1.17.3 --no-document
  - update_rubygems

matrix:
  include:
    # Bleeding edge
    - rvm: ruby-head

    # Running one job to execute DANGER bot
    - rvm: 2.5.0
      script:
        - gem install danger
        - danger

  allow_failures:
    - rvm: ruby-head
