sudo: false
language: ruby
rvm:
  - 2.5.1
services:
  - postgresql
addons:
  chrome: stable
before_install:
  - gem install bundler -v 1.12.5
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 http://localhost &
before_script:
  - cp test/rails_app/config/database.yml.travis test/rails_app/config/database.yml
  - psql -c 'create database rails_app_test;' -U postgres
