language: ruby
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  # - 2.5.0 The latest version is in the include clause and runs with danger.
before_install:
  - gem i rubygems-update -v '<3' && update_rubygems
  - gem install bundler --no-document

matrix:
  include:
    # Bleeding edge
    - rvm: ruby-head

    # Running one job to execute DANGER bot
    - rvm: 2.5.0
      script:
        - gem install danger
        - danger

  allow_failures:
    - rvm: ruby-head
